### ISSUE TITLE
Compatibility with Tailwind v2

### ISSUE THREAD

**Issue by ingageco** [aparajita/tailwind-ionic#2]
Thank you for creating this needed package. Does it have compatibility with Tailwind V2? 

I'm stuck at v2 because of needing to disable purge and generate all possible classes in one file.

**Comment by aparajita** [comment]
I have no idea, have you tried? If the plugin API has not changed it should work.

Why would you need to generate all possible classes? That's enormously wasteful as the majority of them are never used. As for generating all classes in one file, you can use the Tailwind v3 CLI to do that.

**Comment by ingageco** [comment]
@aparajita I apologize - Github never notified me of your reply. We generate all classes because we supply HTML for components via an API. Allows us to dynamically build new views without needing to update the app.

**Comment by aparajita** [comment]
@ingageco 2 minutes of searching found the solution. Did you try this?

https://github.com/tailwindlabs/tailwindcss/discussions/6557#discussioncomment-2880703

**Comment by ingageco** [comment]
@aparajita I appreciate the condescending attitude. I'm fully capable of searching and don't need help - I asked a question about your repo and you answered it.

**Comment by aparajita** [comment]
@ingageco Sheesh, I'm trying to help you out here. Did you try that solution? It would allow you to use Taliwind 3 and generate all classes in a single file.

**Comment by ingageco** [comment]
If your "2 minutes of searching" comment wasn't backhanded, then thank you. But again, i did not ask for help with that issue. I was only asking if your package supported v2, and answered you when you asked why.
